// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogLG_Ability, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_AI, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_AbilityManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_CaseManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_CharacterManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_DebugManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_Gadget, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_GameInstanceSubsystem, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_GameMode, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_GameplayEffect, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_GameplayTagManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_GameState, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_GizboManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_LevelManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_MusicManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_PlayerCameraManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_PlayerCharacter, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_PlayerController, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_PlayerManager, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_PlayerState, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_StateTree, Log, All)
DECLARE_LOG_CATEGORY_EXTERN(LogLG_UIManager, Log, All)